# Generated by Django 4.1.7 on 2023-04-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_survote_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survote_user',
            name='user_type',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'VOTER')], default='VOTER', max_length=6),
        ),
    ]
